[package]
name = "music"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
#dioxus = { version = "0.6.1", features = ["mobile", "hooks", "html", "signals", "web", "desktop"] }
# mp3-metadata = "0.3.4"
# serde = { version = "1.0.215", features = ["derive"] }
# serde_json = "1.0.133"

#diesel = { version = "2.2.0", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
#libsqlite3-sys = { version = "0.30", features = ["bundled"] }
#dotenvy = "0.15"
id3 = "1.15.0"
rand = "0.8.5"
tokio = "1.41.1"
http = "1.1.0"
http-range = "0.1.5"
dioxus-logger = "0.6.0"
tracing = "0.1.41"
crossbow = "0.2.3"
#tensorflow = "0.21.0"
anyhow = "1.0.94"

macroquad = "0.4.9"

[package.metadata.android]
android_version = 28
target_sdk_version = 28
min_sdk_version = 26

build_targets = ["armv7-linux-androideabi", "aarch64-linux-android", "i686-linux-android", "x86_64-linux-android" ]

# [package.metadata.android]
# build_targets = [ "armv7-linux-androideabi", "aarch64-linux-android" ]
