[package]
name = "music"
version = "0.1.0"
edition = "2021"

[lib]
name = "music"

[dependencies]
dioxus = { version = "0.6", features = ["mobile", "hooks", "html", "signals"] }
id3 = "1.15.0"
rand = "0.8.5"
tokio = "1.41.1"
http = "1.1.0"
http-range = "0.1.5"
dioxus-logger = "0.6.0"
crossbow = "0.2.3"
rodio = "0.20"
anyhow = "1.0.94"
android_logger = "0.14.1"
log = "0.4.22"
ndarray = "0.16"
ndarray-npy = "0.9"
tracing = "0.1.41"
tracing-android = "0.2.0"
tracing-log = "0.2.0"

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"

[package.metadata.android]
android_version = 33
target_sdk_version = 33
min_sdk_version = 26

build_targets = ["armv7-linux-androideabi", "aarch64-linux-android", "i686-linux-android", "x86_64-linux-android" ]

# [package.metadata.android]
# build_targets = [ "armv7-linux-androideabi", "aarch64-linux-android" ]
