[package]
name = "music"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "0.6.0", features = ["mobile", "hooks", "html", "signals", "web", "desktop"] }
# mp3-metadata = "0.3.4"
# serde = { version = "1.0.215", features = ["derive"] }
# serde_json = "1.0.133"

#diesel = { version = "2.2.0", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
#libsqlite3-sys = { version = "0.30", features = ["bundled"] }
#dotenvy = "0.15"
id3 = "1.15.0"
rand = "0.8.5"
tokio = "1.41.1"
http = "1.1.0"
http-range = "0.1.5"
dioxus-logger = "0.6.0"
tracing = "0.1.41"
crossbow = "0.2.3"
rand_distr = "0.4.3"

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
#macroquad = "0.4.13"
#slint = { version="1.8.0", features=["backend-android-activity-06"]}
#rodio = "0.20.1"
