[package]
name = "music"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "0.5.6", features = ["desktop", "web", "signals"] }
mp3-metadata = "0.3.4"
reqwest = {version="0.12.9", features=["blocking", "json"]}
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"

diesel = { version = "2.2.0", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
libsqlite3-sys = { version = "0.30", features = ["bundled"] }
dotenvy = "0.15"
id3 = "1.15.0"
rand = "0.8.5"
tokio = "1.41.1"
http = "1.1.0"
http-range = "0.1.5"
rodio = "0.20.1"
